"""Test functional al fluxurilor principale pe dev/preview.py (date din dev/mock-gas.js). Rulare: python3 dev/flow.py.
Selectori pentru UI-ul „Panou split-flap”; actualizeaza-i cand se schimba markup-ul."""
import os
from playwright.sync_api import sync_playwright
errs=[]
def ok(c,m): print(("OK  " if c else "FAIL"), m)
with sync_playwright() as p:
    b=p.chromium.launch(executable_path=os.environ.get("CHROMIUM_PATH", "/opt/pw-browsers/chromium"))
    pg=b.new_page(viewport={'width':1440,'height':900}, ignore_https_errors=True)
    pg.on("pageerror", lambda e: errs.append(str(e)))
    pg.goto("http://localhost:8080/"); pg.wait_for_timeout(1000)
    ok(pg.locator(".row").count()==6, "6 active rows")
    VT=500  # View Transitions: randarea rulează după captură (lent în Chromium headless)
    pg.click(".zchip[data-zone='Interfață']"); pg.wait_for_timeout(VT)
    ok(pg.locator(".row").count()==2, "zone filter Interfață -> 2")
    pg.click(".zchip[data-zone='Interfață']"); pg.wait_for_timeout(VT)
    pg.click("[data-status='all']"); pg.wait_for_timeout(VT); ok(pg.locator(".row").count()==7, "Toate -> 7 (includes resolved)")
    pg.click("[data-status='active']"); pg.wait_for_timeout(VT)
    pg.keyboard.press("/"); pg.keyboard.type("safari"); pg.wait_for_timeout(100)
    ok(pg.locator(".row").count()==1, "search safari -> 1")
    pg.keyboard.press("Escape"); pg.keyboard.press("Escape")
    pg.locator("body").click(position={'x':700,'y':800})
    pg.keyboard.press("j"); pg.wait_for_timeout(VT)
    ok(pg.locator(".row[aria-current='true']").count()==1, "j selects a row")
    pg.keyboard.press("n"); pg.wait_for_timeout(VT)
    ok(pg.locator("#newForm").count()==1, "n opens form")
    pg.click("#nf-submit"); pg.wait_for_timeout(100)
    ok(pg.locator("#nf-reporter-err").count()==1, "validation error on empty name")
    pg.fill("#nf-reporter","Test User"); pg.fill("#nf-title","Exportul CSV nu are diacritice")
    pg.click("[data-zone-pick='Raportare']"); pg.click("[data-prio-pick='ridicata']")
    pg.fill("#nf-desc","pasi")
    pg.click("#nf-submit"); pg.wait_for_timeout(1500)
    ok("TIS-15" in pg.inner_text("#panelInner"), "created TIS-15")
    ok(pg.locator(".row[data-id='TIS-15']").count()==1, "TIS-15 in list")
    pg.click("[data-open='TIS-15']"); pg.wait_for_timeout(VT)
    pg.fill("#cm-text","Adaug un detaliu"); pg.click(".composer button[type=submit]"); pg.wait_for_timeout(800)
    ok("Adaug un detaliu" in pg.inner_text("#panelInner"), "comment added")
    # admin
    pg.click("#adminBtn"); pg.fill("#pinInput","0000"); pg.click("#pinSubmit"); pg.wait_for_timeout(600)
    ok(pg.is_visible("#pinErr"), "wrong pin shows error")
    pg.fill("#pinInput","1234"); pg.click("#pinSubmit"); pg.wait_for_timeout(600)
    ok(pg.is_visible(".tab[data-page='jurnal']"), "admin login -> jurnal tab")
    pg.click(".row[data-id='TIS-12']"); pg.wait_for_timeout(VT)
    pg.click("[data-set-status='in_lucru']"); pg.wait_for_timeout(600)
    ok("În lucru" in pg.inner_text(".row[data-id='TIS-12']"), "status change applied")
    pg.select_option("#ad-zone","Date"); pg.wait_for_timeout(600)
    ok(pg.locator(".row[data-id='TIS-12'] .r-zone[data-z='date']").count()==1, "zone change applied")
    pg.click("[data-act='edit']"); pg.fill("#ed-title","Butonul Export nu merge pe Safari 17"); pg.click("form.edit button[type=submit]"); pg.wait_for_timeout(600)
    ok("Safari 17" in pg.inner_text(".row[data-id='TIS-12']"), "edit title applied")
    pg.click("[data-act='archive-ask']"); pg.click("[data-act='archive']"); pg.wait_for_timeout(700)
    ok(pg.locator(".row[data-id='TIS-12']").count()==0, "archived removed from list")
    pg.click("[data-status='archive']"); pg.wait_for_timeout(900)
    ok(pg.locator(".row[data-id='TIS-12']").count()==1, "archive shows TIS-12")
    pg.click(".row[data-id='TIS-12']"); pg.wait_for_timeout(VT); pg.click("[data-act='restore']"); pg.wait_for_timeout(900)
    pg.click("[data-status='active']"); pg.wait_for_timeout(VT)
    ok(pg.locator(".row[data-id='TIS-12']").count()==1, "restored back to active")
    pg.click(".tab[data-page='news']"); pg.wait_for_timeout(900)
    pg.click("#newsNewBtn"); pg.wait_for_timeout(200); pg.fill("#nw-title","Test anunt"); pg.fill("#nw-body","Corp"); pg.click("[data-ntype='fix']"); pg.click("#nw-submit"); pg.wait_for_timeout(800)
    ok(pg.locator(".news-item").count()==3, "news published")
    pg.click(".tab[data-page='jurnal']"); pg.wait_for_timeout(900)
    ok("status: În lucru" in pg.inner_text("#journal"), "journal humanized")
    pg.click("#adminBtn"); pg.wait_for_timeout(200)
    ok(not pg.is_visible(".tab[data-page='jurnal']"), "logout hides jurnal")
    b.close()
print("page errors:", errs or "none")
